// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "label_gross_weight3.h"

/////////////////////////////////////////////////////////////////////////////
// CLabel_gross_weight3

IMPLEMENT_DYNCREATE(CLabel_gross_weight3, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLabel_gross_weight3 properties

/////////////////////////////////////////////////////////////////////////////
// CLabel_gross_weight3 operations
