//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PMSHJ.rc
//
#define IDB_BITMAP_WEIGHT_TITLE         3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PMSHJ_FORM                  101
#define IDS_STR_SETTINGS                101
#define IDS_STR_REPORT                  102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDS_STR_PRINT                   104
#define IDS_STR_SCAN                    105
#define IDS_STR_STOP                    106
#define IDS_STR_LENGTH                  107
#define IDS_STR_WIDTH                   108
#define IDS_STR_HEIGHT                  109
#define IDS_STR_VOLUME                  110
#define IDS_STR_NET_WT                  111
#define IDS_STR_GROSS_WT                112
#define IDS_STR_TARE_WT                 113
#define IDS_STR_PRETARE_WT              114
#define IDS_STR_SCAN_DATA_DSPL          115
#define IDS_STR_WF_CODE                 116
#define IDS_STR_PKG_NUM                 117
#define IDS_STR_WT_SETTINGS             118
#define IDR_POPUP_EDIT                  119
#define IDS_STR_COM_PORT_ST             119
#define ID_STATUSBAR_PANE1              120
#define IDS_STR_READ_UDF                120
#define ID_STATUSBAR_PANE2              121
#define IDS_STR_SAVE_UDF                121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_STR_INSP_PARAMS             126
#define IDS_STR_CODE_TEST               127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_STR_OK                      129
#define IDR_PMSHJTYPE                   130
#define IDS_STR_CANCEL                  130
#define IDS_STR_ZERO_WT                 131
#define IDS_STR_SET_TARE_WT             132
#define IDS_STR_SET_PTARE_WT            133
#define IDS_STR_SL_PORT_PARAMS          134
#define IDS_STR_SEL_COM_PORT            135
#define IDS_STR_SEL_PORT                136
#define IDS_STR_WS_INPUT                137
#define IDS_STR_WS_OUTPUT               138
#define IDS_STR_PRINTER                 139
#define IDS_STR_SET_PARAMS              140
#define IDS_STR_COM_PARAMS              141
#define IDS_STR_BAUD_RATE               142
#define IDS_STR_BYTE_SIZE               143
#define IDS_STR_PARITY                  144
#define IDS_STR_STOP_BIT                145
#define IDS_STR_WT_SCALE_TYPE           146
#define IDS_STR_DATA_TRANS_TYPE         147
#define IDS_STR_CONT                    148
#define IDS_STR_STABLE                  149
#define IDS_STR_EDIT_SAVE_UDF           150
#define IDS_STR_NEXT_LINE               151
#define IDS_STR_CAM_HT                  152
#define IDS_STR_MIN_JOB_HT              153
#define IDS_STR_MAX_JOB_HT              154
#define IDS_STR_MIN_JOB_WT              155
#define IDS_STR_SPOT_RECT_SIZE          156
#define IDS_STR_CODE_LEN                157
#define IDS_STR_CUBE                    158
#define IDS_STR_FLIP_VERT               159
#define IDS_STR_FLIP_HORZ               160
#define IDS_STR_SHOW_RECS               161
#define IDS_STR_DEL_REC                 162
#define IDS_STR_SCAN_RECS               163
#define IDS_STR_TRANS_NUM               164
#define IDS_STR_ENTER_MAN               165
#define IDS_STR_SCAN_CODE               166
#define IDS_STR_FETCH_RECS              167
#define IDS_STR_EXPORT                  168
#define IDS_STR_DONE                    169
#define IDS_STR_SCAN_STOPPED            170
#define IDS_STR_3DCAM_NOT_INIT          171
#define IDS_STR_SCAN_UP                 172
#define IDS_STR_WT_NOT_READ             173
#define IDS_STR_STOP_SCAN               174
#define IDS_STR_GRAB_ERR                175
#define IDS_STR_SCANDATA_INVALID        176
#define IDS_STR_SCADATA_DSPLD           177
#define IDS_STR_CODE_RCD                178
#define IDS_STR_DATA_SAVED              179
#define IDS_STR_DATA_NOT_SAVED          180
#define IDS_STR_SCAN_OVER               181
#define IDS_STR_APP_RUNNING             182
#define IDS_STR_LIC_EXPIRED             183
#define IDS_STR_DONGLE_MISSING          184
#define IDS_STR_WRONG_CAM_SL            185
#define IDS_STR_DB_ERR                  186
#define IDS_STR_ENTER_TRAN_ID           187
#define IDS_STR_REPORT_NOT_CREATED      188
#define IDS_STR_DLOAD_NOTFOUND          189
#define IDS_STR_UDF_READ_ERR            190
#define IDS_STR_SCALE_ERR               191
#define IDS_STR_OPTIONS                 192
#define IDS_STR_EXIT                    193
#define IDS_STR_SAVE_UDF_FILE           194
#define IDS_STR_SAVE_UDF_CAPTION        195
#define IDS_STR_CODEREAD_ABORTED        196
#define IDS_STR_SET_ZERO_WT             197
#define IDS_STR_TRANS_ID_EMPTY          198
#define IDS_STR_SCAN_FOR_TRNSPORTER     199
#define IDR_THEME_MENU                  200
#define IDS_STR_CALIB_MSG               200
#define ID_SET_STYLE                    201
#define IDS_STR_CALIBRATION             201
#define IDS_STR_CAM_ADJ                 202
#define IDS_STR_AUTO_ADJ                203
#define IDS_STR_PRINT_PARAMS            204
#define ID_VIEW_APPLOOK_WIN_2000        205
#define IDS_STR_SAVE_PICT               205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define IDS_STR_TEST_PRINT              206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define IDS_STR_LOGO_FILE               207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define IDS_STR_FREIGHT_PARAMS          208
#define ID_VIEW_APPLOOK_VS_2005         209
#define IDS_STR_AIR_FREIGHT             209
#define ID_VIEW_APPLOOK_VS_2008         210
#define IDS_STR_SEA_FREIGHT             210
#define IDS_STR_DATA_SEND_PARAMS        211
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDB_BITMAP_LENGTH               311
#define IDB_BITMAP_WIDTH                312
#define IDB_BITMAP_HEIGHT               313
#define IDB_BITMAP_VOLUME               315
#define IDB_BITMAP_VERT_SEP_FULL        317
#define IDB_BITMAP_HORZ_800             318
#define IDB_BITMAP_VERT_SEP_HALF        319
#define IDI_PRINT                       320
#define IDI_WT_ZERO                     321
#define IDI_SETTINGS                    322
#define IDI_DATA                        324
#define IDI_REPORT                      325
#define IDI_ICON1                       326
#define IDI_EXIT                        326
#define IDB_BITMAP_VERT_SEP_266         327
#define IDB_BITMAP_WT_OK                329
#define IDB_BITMAP_WT_NOK               330
#define IDB_BITMAP_MEAS_OK              331
#define IDB_BITMAP_HORZ_666             332
#define IDB_BITMAPMEAS_NOK              333
#define IDB_BITMAP_MEAS_NOK             333
#define IDI_DATA_OUTPUT                 334
#define IDB_BITMAP_LT_LOGO              335
#define IDD_DLG_SETTINGS                336
#define IDD_DLG_WT_SETTINGS             338
#define IDD_DLG_UDF_FILE                340
#define IDD_DLG_REPORT                  342
#define IDD_DLG_INSP_PARAMS             344
#define IDB_BITMAP_HORZ_172             346
#define IDD_DLG_OPTIONS                 347
#define IDD_DLG_CALIB                   349
#define IDB_BITMAP_LOGO_HJ              351
#define IDD_DLG_PRINT_PARAMS            352
#define IDI_START                       356
#define IDI_STOP                        357
#define IDB_BITMAP_TOP_BANNER           358
#define IDB_BITMAP_GRID_COL1            359
#define IDB_BITMAP_GRID_COL2            360
#define IDB_BITMAP_GRID_COL3            361
#define IDB_BITMAP_GRID_COL4            362
#define IDB_BITMAP_GRID_COL5            363
#define IDB_BITMAP_CENTRAL_BANNER       364
#define IDB_BITMAP_RH_BANNER            365
#define IDB_BITMAP_MM                   366
#define IDB_BITMAP_M3                   367
#define IDB_BITMAP_KG                   368
#define IDI_ICON2                       369
#define IDI_REPORT_CLKD                 369
#define IDI_SETTINGS_CLKD               370
#define IDI_START_CLKD                  371
#define IDI_ICON3                       372
#define IDI_STOP_CLKD                   372
#define IDI_EXIT_CLKD                   373
#define IDD_DLG_FREIGHT_PARAMS          374
#define IDI_PRINT_CLKD                  376
#define IDI_AIR_FREIGHT                 377
#define IDI_SEA_FREIGHT                 378
#define IDI_SEA_FREIGHT_CLKD            379
#define IDI_AIR_FREIGHT_CLKD            380
#define IDB_BITMAP_SEA_FREIGHT_RATE     381
#define IDB_BITMAP_AIR_FREIGHT_RATE     382
#define IDB_BITMAP_WT_FREIGHT_RATE      383
#define IDB_BITMAP_SLIDER_ON            384
#define IDB_BITMAP_SLIDER_OFF           385
#define IDD_DLG_DATA_SEND               386
#define IDB_BITMAP_DATA_LOGGING         388
#define IDB_BITMAP_DATA_FAIL            389
#define IDB_BITMAP_DATA_OK              390
#define IDB_BITMAPDATA_NOT_DONE         391
#define IDD_DIALOG1                     392
#define IDD_DLG_SERIAL_COMM             415
#define IDC_CMB_BAUD_RATE               420
#define IDC_CMB_BYTE_SIZE               421
#define IDC_CMB_PARITY                  422
#define IDC_CMB_STOP_BIT                423
#define IDC_BN_SET_ZERO_WT              425
#define IDC_RADIO_WEIGH_SCALE_TYPR      430
#define IDC_RADIO_WEIGH_SCALE_CH340     431
#define IDC_RADIO2                      435
#define IDC_RADIO8                      436
#define IDC_RAD_CODE_SUFFIX             436
#define IDC_RADIO_DATA_TRANS_TYPE       440
#define IDC_RADIO4                      445
#define IDC_LIST_COM_PORTS              450
#define IDC_PIC_LENGTH                  1000
#define IDC_PIC_WIDTH                   1001
#define IDC_PIC_HEIGHT                  1002
#define IDC_LABEL_LENGTH                1003
#define IDC_PIC_DATA                    1003
#define IDC_LABEL_WIDTH                 1004
#define IDC_LABEL_HEIGHT                1005
#define IDC_PIC_VOLUME                  1006
#define IDC_LABEL_VOLUME                1007
#define IDC_PIC_WEIGHT                  1008
#define IDC_LABEL_WEIGHT                1009
#define IDC_PIC_DATA_LIGHT              1009
#define IDC_PIC_VERT_SEP                1010
#define IDC_PIC_2DIMAGE                 1011
#define IDC_LABEL_WEIGHT2               1012
#define IDC_BN_ZERO_WT                  1013
#define IDC_PIC_LOGO                    1013
#define IDC_LABEL_WEIGHT3               1014
#define IDC_LABEL_WEIGHT4               1015
#define IDC_LABEL_WEIGHT5               1016
#define IDC_LABEL_WEIGHT6               1017
#define IDC_PIC_HORZ_SEO                1018
#define IDC_PIC_VERT_SEP2               1019
#define IDC_LABEL_LEN_UNIT              1020
#define IDC_LABEL_WID_UNIT              1021
#define IDC_LABEL_HT_UNIT               1022
#define IDC_LABEL_WT_UNIT               1023
#define IDC_LABEL_VOL_UNIT              1024
#define IDC_BN_DATA_OUTPUT              1025
#define IDC_PIC_HORZ_SEP_SMALL          1025
#define IDC_BN_SETTINGS                 1026
#define IDC_BN_DATA                     1027
#define IDC_BN_ZERO_ACTION              1027
#define IDC_BN_REPORT                   1028
#define IDC_BN_EXIT                     1029
#define IDC_LABEL_WEIGHT12              1030
#define IDC_LABEL_WEIGHT13              1031
#define IDC_LABEL_GROSS_WEIGHT          1032
#define IDC_LABEL_TARE                  1032
#define IDC_LABEL_WEIGHT14              1033
#define IDC_LABEL_WEIGHT15              1034
#define IDC_PIC_WT_STATUS               1034
#define IDC_LABEL_GROSS_WEIGHT2         1035
#define IDC_PIC_VOLUME2                 1036
#define IDC_LABEL_GROSS_WEIGHT4         1037
#define IDC_LABEL_PRETARE               1037
#define IDC_PIC_VERT_SEP3               1038
#define IDC_PIC_HORZ_SEP_666            1039
#define IDC_LABEL_WEIGHT18              1040
#define IDC_LABEL_GROSS_WEIGHT3         1040
#define IDC_LABEL_MSG                   1040
#define IDC_BN_TARE_ACTION              1041
#define IDC_LABEL_WEIGHT20              1042
#define IDC_BUTTON1                     1042
#define IDC_BN_WT_SETTINGS              1042
#define IDC_BN_SET_TARE                 1042
#define IDC_BN_SET_COM_PARAMS           1042
#define IDC_BN_SCAN_BARCODE             1042
#define IDC_BN_CALIB                    1042
#define IDC_BN_TEST_PRINT               1042
#define IDC_BN_TEST_FOOT_SWITCH         1042
#define IDC_PRINT                       1042
#define IDC_LABEL_                      1043
#define IDC_LABEL_PK_NO                 1043
#define IDC_EDIT_MACHINE_NAME           1043
#define IDC_BN_SET_PRETARE              1043
#define IDC_BN_FETCH_RECORDS            1043
#define IDC_BN_COMPORT_SETTINGS         1044
#define IDC_BN_PRE_TARE_ACTION          1045
#define IDC_BN_READ_UDF_FILE            1045
#define IDC_EDIT_TARE_WT                1046
#define IDC_BN_READ_UDF_FILE2           1046
#define IDC_BN_SAVE_UDF_FILE            1046
#define IDC_EDIT_PRETARE_WT             1047
#define IDC_RICHEDIT2_TXT               1047
#define IDC_EDIT_MIN_WT                 1047
#define IDC_BN_INSP_PARAMS              1047
#define IDC_BN_ZERO_ACTION2             1048
#define IDC_BN_PTINT                    1048
#define IDC_BN_PRINT                    1048
#define IDC_EDIT_ZERO_WT                1048
#define IDC_RADIO_WEIGH_CALE_INPUT      1048
#define IDC_BN_CODE_TEST                1048
#define IDC_BN_SCAN                     1049
#define IDC_RADIO3                      1049
#define IDC_BN_PRINT_PARAMS             1049
#define IDC_LIST_DATABASE               1050
#define IDC_EDIT1                       1051
#define IDC_EDIT_TRANS_NO               1051
#define IDC_EDIT_STA_NAME               1051
#define IDC_EDIT_CODE_TEST              1051
#define IDC_EDIT_WT_ACC                 1051
#define IDC_EDIT_LABEL_LENGTH           1051
#define IDC_EDIT_SEAFREIGHT_RATE        1051
#define IDC_EDIT_URL                    1051
#define IDC_EDIT_PWD                    1051
#define IDC_EDIT_MIN_CODE_VAL           1051
#define IDC_BN_SHOW_RECORDS             1052
#define IDC_EDIT_data_stamp             1052
#define IDC_EDIT_LABEL_WIDTH            1052
#define IDC_EDIT_AIRFREIGHT_RATE        1052
#define IDC_EDIT_MAX_CODE_LEN           1052
#define IDC_EDIT_URL2                   1052
#define IDC_BUTTON3                     1053
#define IDC_BN_EXPORT_TO_XLS            1053
#define IDC_EDIT_wk_date                1053
#define IDC_BN_FREIGHT_PARAMS           1053
#define IDC_EDIT_WEIGHTFREIGHT_RATE     1053
#define IDC_RADIO_PRINTER               1054
#define IDC_EDIT_tran_no                1054
#define IDC_EDIT_pack_no                1055
#define IDC_EDIT_pack_l                 1056
#define IDC_EDIT_pack_w                 1057
#define IDC_CHK_FLIP_VERT               1057
#define IDC_EDIT_pack_h                 1058
#define IDC_CHK_FLIP_HORZ               1058
#define IDC_EDIT_pack_v                 1059
#define IDC_EDIT_MIN_JOB_HT             1059
#define IDC_EDIT_v_unit                 1060
#define IDC_EDIT_MAX_JOB_HT             1060
#define IDC_EDIT_pack_net               1061
#define IDC_EDIT_SPOT_RECT_SIZE         1061
#define IDC_EDIT_pack_gross             1062
#define IDC_EDIT_CAM_HT                 1062
#define IDC_EDIT_pack_tare              1063
#define IDC_EDIT_CODE_LEN               1063
#define IDC_EDIT_pack_ptare             1064
#define IDC_CHK_ISCUBOID                1064
#define IDC_EDIT_wt_unit                1065
#define IDC_BUTTON2                     1065
#define IDC_BN_DELETE_RECORD            1065
#define IDC_BN_OPTIONS                  1065
#define IDC_EDIT_CAM_ALIGN_RECT_SIZE    1065
#define IDC_BN_LOGO_FILE                1065
#define IDC_EDIT_upd_flag               1066
#define IDC_RADIO1                      1066
#define IDC_RADIO_TRAN_NUM              1066
#define IDC_RADIO_LANGUAGE              1066
#define IDC_RADIO_P5                    1066
#define IDC_RADIO_DSPL_ACC              1066
#define IDC_RADIO_CALIB_CAMHEIGHT       1066
#define IDC_BN_CALIBRATION              1066
#define IDC_EDIT_del_mark               1067
#define IDC_RADIO_DIM_UNIT              1067
#define IDC_EDIT_CODE_LEN2              1067
#define IDC_EDIT_MAX_CODE_VAL           1067
#define IDC_RADIO5                      1068
#define IDC_RADIO6                      1069
#define IDC_RADIO7                      1070
#define IDC_STATIC_SEL_PKG              1071
#define IDC_RADIO_GRAM                  1072
#define IDC_CHECK1                      1074
#define IDC_CHK_SERIAL_SCANNER          1074
#define IDC_CHK_LOGO                    1074
#define IDC_CHK_SEND_DATA               1074
#define IDC_CHK_ENABLE_WT               1074
#define IDC_CHK_USE_CODE_RANGE          1074
#define IDC_RADIO9                      1075
#define IDC_CHK_NET_WT                  1076
#define IDC_CHK_GROSS_WT                1077
#define IDC_CHK_TARE_WT                 1078
#define IDC_CHK_PRETARE_WT              1079
#define IDC_CHK_PRINT_LABEL             1080
#define IDC_CMB_CODE                    1081
#define IDC_CMB_FONT                    1082
#define IDC_EDIT_CODE_HT                1083
#define IDC_EDIT_NUM_PRINTS             1084
#define IDC_EDIT_CORPORATE              1086
#define IDC_EDIT_PRODUCT                1087
#define IDC_EDIT_PRINTER                1088
#define IDC_CHK_PRINT_CNFM              1089
#define IDC_RADIO_TRG_SOURCE            1091
#define IDC_RADIO_FOOT_SWITCH           1092
#define IDC_BUTTON4                     1093
#define IDC_BN_STOP                     1093
#define IDC_BN_DATA_SEND_PARAMS         1093
#define IDC_MSFLEXGRID                  1094
#define IDC_STATIC_TEXT_LEN             1095
#define IDC_STATIC_TEXT_WIDTH           1096
#define IDC_STATIC_TEXT_HT              1097
#define IDC_STATIC_TEXT_VOL             1098
#define IDC_STATIC_TEXT_WIDTH2          1099
#define IDC_STATIC_TEXT_WT              1099
#define IDC_STATIC_RH_BANNER            1100
#define IDC_RADIO_SCANNER               1101
#define IDC_RADIO11                     1102
#define IDC_RADIO10                     1103
#define IDC_STATIC_LOGO_FILE            1104
#define IDC_BN_AIR_FREIGHT              1105
#define IDC_BN_SEA_FREIGHT              1106
#define IDC_STATIC_SEAFR_CN             1106
#define IDC_EDIT_KEY                    1110
#define IDC_EDIT_OPERATING_MODE         1111
#define IDC_EDIT_KEY2                   1111
#define IDC_CHECK2                      1113
#define IDC_CHK_ENABLE_ADDR2            1113

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        394
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1114
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
